<?php

/**
 * Retrieve the current OpenLayers JS library version filename.
 *
 * @return String
 *   The OpenLayers JS library filename to use.
 */
function iform_openlayers_get_file() {
  $config = \Drupal::configFactory()->getEditable('iform.openlayers.settings');

  switch($config->get('openlayers_mode', 'custom')){
    case 'debug':
        return 'OpenLayers-debug.js';
    case 'minimised':
        return 'OpenLayers-min.js';
    case 'custom':
    default:
        return 'OpenLayers.js';
  }
}

/**
 * Implement hook_form_FORM_ID_alter
 * We use a single radio group to decide if we use the custom, minimised or
 * full debug version of the OpenLayers.js file.
 */
function iform_openlayers_form_iform_settings_form_alter(&$form, $form_state, $form_id) {
  $config = \Drupal::configFactory()->getEditable('iform.openlayers.settings');

  $form['openlayers_mode'] = [
    '#type' => 'radios',
    '#title' => t('Type of OpenLayers.js file used'),
    '#options' => ['custom' => t('IForm Custom Build'),
                   'minimised' => t('Official Minimised Version'),
                   'debug' => t('Debug')],
    '#description' => t('Whether to use the Indicia custom build of OpenLayers, the official ' .
                        'minimised version, or the full debug version. The custom build has several classes ' .
                        'omitted to further reduce the size, improving download times.'),
    '#required' => TRUE,
    '#default_value' => $config->get('openlayers_mode', 'custom')
  ];
  $form['submit']['#weight'] = 1000;
  $form['#submit'][] = 'iform_openlayers_iform_settings_form_submit';
}

/**
 * Additional Form submission function, used to set the version of the OpenLayers file we are going to use.
 */
function iform_openlayers_iform_settings_form_submit($form, &$form_state) {
  $config = \Drupal::configFactory()->getEditable('iform.openlayers.settings');
  $values = $form_state->getValues();
  $config->set('openlayers_mode', $values['openlayers_mode']);
  $config->save();
}
