<?php

use Drupal\Core\Url;

/* -----------------------------------------------------------------

Public API

------------------------------------------------------------------ */

/**
 * Provide a URL to be used for AJAX requests.
 *
 * @param ?int $nid
 *   Node ID.
 * @param int|string $index
 *   Array index used to define how to process the post into an indicia format.
 *
 * @return string
 *   A ready to be used url.
 *
 * @see iform_proxy_redirect()
 */
function iform_ajaxproxy_url($nid, $index) {
  return Url::fromRoute(
    'iform_ajaxproxy.callback',
    [],
    [
      'absolute' => TRUE,
      'query' => [
        'node' => empty($nid) ? '' : $nid,
        'index' => $index,
      ],
    ])->toString();
}
