commerce_claim_gift_aid.commerce_gift_aid_text:
  type: config_object
  mapping:
    gift_aid_text:
      type: text
      label: 'Gift aid text'
commerce_order.commerce_order_item_type.*.third_party.commerce_claim_gift_aid:
  type: mapping
  label: 'Commerce gift aid order item type'
  mapping:
    gift_aid:
      type: string
      label: 'Is eligible for gift aid'
