htmlmail.settings:
  type: config_object
  label: 'HTML Mail label settings'
  mapping:
    debug:
      type: boolean
      label: 'Enable the template debug'
    theme:
      type: string
      label: 'The theme used to send the email'
    html_with_plain:
      type: boolean
      label: 'Send the email as text plain'
    postfilter:
      type: string
      label: 'The filter used on email body'
    use_mail_mime:
      type: boolean
      label: 'Use the PEAR \Mail_mime class'
    test:
      type: mapping
      label: 'Mail header data for sending out the test email message'
      mapping:
        to:
          type: email
          label: 'The recipient of the test email message'
        subject:
          type: label
          label: 'The subject of the test email message'
        body:
          type: sequence
          label: 'The content of the test email message'
          sequence:
            type: text
            label: 'The body text of the test email message'
        class:
          type: string
          label: 'The mailsystem class used for the test email message'
