forum_access.settings:
  type: config_object
  label: 'Forum Access settings'
  mapping:
    forum_access_roles_gids:
      type: sequence
      label: 'Role - Grant Id mapping array'
      sequence:
        type: integer
        label: 'Grant ID'
