field.formatter.settings.show_email_address:
  type: mapping
  label: 'Show Email Settings'
  mapping:
    hide_user_one:
      type: int
      label: 'User one'
    email_mailto:
      type: int
      label: 'Enable mailto link'
    hide_per_role:
      type: mapping
      label: 'Configuration for the add role action'
      mapping:
        rid:
          type: string
          label: 'The ID of the role to add'
        label:
          type: label
          label: 'Label'
