<?php

namespace Drupal\Iform;

use Drupal\Core\StringTranslation\StringTranslationTrait;

class IformPermissions {

  use StringTranslationTrait;

  /**
   * Returns an array of permissions.
   * Generates dynamic permissions required for Indicia forms.
   *
   * @return array
   */
  public function permissions() {
    $permissions = [];
    $helpersLoaded = FALSE;

    if (\Drupal::moduleHandler()->moduleExists('iform_custom_forms')) {
      // Enable autoloader for classes in iform_custom_forms module.
      \Drupal::service('iform_custom_forms.list');
    }

    // Get list of iform nodes.
    $query = \Drupal::database()->select('node', 'n');
    $query->fields('n', ['nid']);
    $query->condition('type', "iform_page", "=");
    $nids = $query->execute();
    foreach ($nids as $row) {
      $node = \Drupal\node\Entity\Node::load($row->nid);
      if ($node->field_iform->value) {
        if (!$helpersLoaded) {
          iform_load_helpers(['data_entry_helper']);
          $helpersLoaded = TRUE;
        }
        if (!class_exists('iform_' . $node->field_iform->value)) {
          require_once iform_client_helpers_path() . 'prebuilt_forms/' . $node->field_iform->value . '.php';
        }
        if (method_exists('iform_' . $node->field_iform->value, 'get_perms')) {
          $perms = call_user_func(
            ['iform_' . $node->field_iform->value, 'get_perms'], 
            $node->id(),
            $node->params
          );
          foreach ($perms as $perm) {
            $permissions[$perm] = [
              'title' => $this->t($perm),
              'description' => t('Permission generated by Iform prebuilt form'),
            ];
          }
        }
      }
      if (!empty($node->params['view_access_control'])) {
        if (!empty($node->params['permission_name'])) {
          $perm = $node->params['permission_name'];
        }
        else {
          $perm = 'access iform ' . $node->id();
        }
        $permissions[$perm] = [
          'title' => $this->t($perm),
          'description' => t('Permission generated by Iform prebuilt form'),
        ];
      }
    }
    return $permissions;
  }

}
