<?php

use Drupal\Core\Link;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds an option to the IForm settings form to set whether licensing is for
 * records, media, or both.
 */
function iform_licences_form_iform_settings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::configFactory()->get('iform_licences.settings');
  $default = $config->get('licences_mode');
  $default = $default ? $default : 'media';
  $form['iform_licences_mode'] = [
    '#type' => 'details',
    '#title' => t('Indicia licence choices'),
    '#description' => t('Option to apply user licence choice for records and/or media separately.'),
    '#type' => 'radios',
    '#options' => array(
      'records' => t('User can select licence for records only'),
      'media' => t('User can select licence for media (photos etc) only'),
      'records+media' => t('User can select licence for records and media separately'),
    ),
    '#default_value' => $default,
    '#weight' => 49,
  ];
  $form['#submit'][] = 'iform_licences_iform_settings_form_submit';
}

/**
 * Save the mode option on Iform settings form submit.
 */
function iform_licences_iform_settings_form_submit($form, FormStateInterface &$form_state) {
  $config = \Drupal::configFactory()->getEditable('iform_licences.settings');
  $values = $form_state->getValues();
  $config->set('licences_mode', $values['iform_licences_mode']);
  $config->save();
}

/**
 * Implements hook_form_alter().
 *
 * Adds a licence selection control to the user register and profile edit
 * forms.
 */
function iform_licences_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'user_form') {
    $config = \Drupal::configFactory()->getEditable('iform_licences.settings');
    iform_load_helpers(['helper_base']);
    $conn = iform_get_connection_details();
    $readAuth = helper_base::get_read_auth($conn['website_id'], $conn['password']);
    $licences = helper_base::get_population_data([
      'table' => 'licence',
      'extraParams' => $readAuth,
      'cachePerUser' => FALSE,
    ]);
    $licencesMode = $config->get('licences_mode');
    $licencesMode = $licencesMode ? $licencesMode : 'media';
    $licencesApplyTo = explode('+', $licencesMode);
    if (count($licences)) {
      $indiciaUserId = hostsite_get_user_field('indicia_user_id');
      $currentLicenceId = NULL;
      $currentMediaLicenceId = NULL;
      if ($indiciaUserId) {
        $current = helper_base::get_population_data(array(
          'table' => 'users_website',
          'extraParams' => $readAuth + array(
            'user_id' => $indiciaUserId,
            'columns' => 'licence_id,media_licence_id',
          ),
          'caching' => FALSE,
        ));
        $currentLicenceId = $current[0]['licence_id'];
        $currentMediaLicenceId = $current[0]['media_licence_id'];
      }
      $options = [];
      foreach ($licences as $licence) {
        $options[$licence['id']] = "$licence[code]: <a href='$licence[url_readable]'>$licence[title]</a>";
      }
      foreach ($licencesApplyTo as $licenceFor) {
        $label = $licenceFor === 'records' ? t('records') : t('photos and other media');
        $thisLicenceId = $licenceFor === 'records' ? $currentLicenceId : $currentMediaLicenceId;
        $description = t('Select the licence to apply to your @label.', ['@label' => $label]) . ' ';
        // For media only, add some text to recommend CC0 and avoiding commercially valuable images
        if ($licenceFor !== 'records') {
          $description .=  t('If you are happy to select a CC0 or CC BY licence option, that will provide the best chance for your photos to be used in research and conservation. ');
        }
        if ($form_id === 'user_profile_form') {
          // Extra warning shown when changing existing setting.
          if ($thisLicenceId) {
            $description .= t(
              'If you change the selected licence then it will only affect @label you enter from now on.',
              ['@label' => $licenceFor]
            );
          }
          else {
            $siteName = \Drupal::config('system.site')->get('name');
            $description .= '<strong>' . strtoupper(
              t('This licence will also be applied to all the @label you have previously uploaded to @site.',
              [
                '@label' => $label,
                '@site' => $siteName,
              ]
            )) . '</strong>';
            if ($licenceFor === 'media') {
              $description .= strtoupper(
                t(' If you have many thousands of images, it may take a few minutes to apply.',
                [
                  '@label' => $label,
                  '@site' => $siteName,
                ]
              ));
            }
          }
        }
        $form["field_iform_licence_$licenceFor"] = array(
          '#type' => 'radios',
          '#title' => t('<span id="licenceopts">Licence for your @label</span>', ['@label' => $label]),
          '#options' => $options,
          '#description' => $description,
          '#required' => $form_id === 'user_register_form' ? TRUE: FALSE,
          '#default_value' => $thisLicenceId,
        );
        foreach (array_keys($form['actions']) as $action) {
          if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
            $form['actions'][$action]['#submit'][] = 'iform_licences_user_form_submit';
          }
        }
      }
    }
  }
}

/**
 * Submit handler for the register and user profile forms.
 *
 * Saves the licence setting.
 */
function iform_licences_user_form_submit($form, FormStateInterface &$form_state) {
  iform_load_helpers(['submission_builder', 'data_entry_helper']);
  $conn = iform_get_connection_details(NULL);
  $auth = helper_base::get_read_write_auth($conn['website_id'], $conn['password']);
  $indiciaUserId = hostsite_get_user_field('indicia_user_id');
  $conn = iform_get_connection_details();
  if ($indiciaUserId) {
    $formValues = $form_state->getValues();
    $current = helper_base::get_population_data(array(
      'table' => 'users_website',
      'extraParams' => $auth['read'] + array(
        'user_id' => $indiciaUserId,
        'columns' => 'id,licence_id,media_licence_id',
      ),
      'caching' => FALSE
    ));
    $values = [];
    if (count($current)) {
      $currentUw = $current[0];
      $values['id'] = $currentUw['id'];
    }
    else {
      $currentUw = [
        'licence_id' => NULL,
        'media_licence_id' => NULL,
      ];
      $values = [
        'user_id' => $indiciaUserId,
        'website_id' => $conn('website_id', ''),
      ];
    }
    $change = FALSE;
    if (!empty($formValues['field_iform_licence_records']) &&
        $formValues['field_iform_licence_records'] !== $currentUw['licence_id']) {
      $values['licence_id'] = $formValues['field_iform_licence_records'];
      $change = TRUE;
    }
    if (!empty($formValues['field_iform_licence_media']) &&
        $formValues['field_iform_licence_media'] !== $currentUw['media_licence_id']) {
      $values['media_licence_id'] = $formValues['field_iform_licence_media'];
      $change = TRUE;
    }
    if ($change) {
      $s = submission_builder::build_submission($values, array('model' => 'users_website'));
      $r = data_entry_helper::forward_post_to('users_website', $s, $auth['write_tokens']);
      if (!isset($r['success'])) {
        \Drupal::logger('iform')->error('Error occurred when saving a user licence: ' . var_export($r, TRUE));
        hostsite_show_message(var_export($r, TRUE), 'error');
      }
    }
  }

}

/**
 * Implements hook_user_login().
 *
 * Adds a message if the user has not configured their licence settings.
 */
function iform_licences_user_login(UserInterface $account) {
  if (!empty($account->field_indicia_user_id->value)) {
    iform_load_helpers(['helper_base']);
    $conn = iform_get_connection_details();
    $readAuth = helper_base::get_read_auth($conn['website_id'], $conn['password']);
    $current = helper_base::get_population_data(array(
      'table' => 'users_website',
      'extraParams' => $readAuth + [
        'user_id' => $account->field_indicia_user_id->value,
        'columns' => 'media_licence_id'
      ],
      'caching' => FALSE,
    ));
    $currentMediaLicenceId = $current[0]['media_licence_id'];
    if (!isset($currentMediaLicenceId)) {
      \Drupal::messenger()->addMessage(t('You have not yet specified a media licence. This limits the usefulness of your images. @link',
        ['@link' => Link::fromTextAndUrl(t('To set a licence, edit your profile page and select an option.'), $account->toUrl('edit-form'))->toString()]
      ));
    }
  }
}
