<?php

/**
 * Implements hook_theme().
 *
 * Declare a template for the group home pages.
 */
function group_landing_pages_theme($existing, $type, $theme, $path) {
  return [
    'group_landing_page' => [
      'variables' => [
        'group_id' => '',
        'group_title' => '',
        'group_type' => '',
        'description' => '',
        'implicit_record_inclusion' => '',
        'member' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 *
 * Provides suggestions for template names:
 * * group-landing-page--type-<type name>, e.g.
 *   group-landing-page--type-bioblitz.html.twig.
 * * group-landing-page--id-<id>, e.g. group-landing-page--id-123.html.twig.
 */
function group_landing_pages_theme_suggestions_group_landing_page(array $variables) {
  $suggestions = [];
  // Lowest priority (least specific) first.
  $suggestions[] = 'group_landing_page__type_' . preg_replace('/[^a-z]/', '-', strtolower($variables['group_type']));
  $suggestions[] = "group_landing_page__id_$variables[group_id]";
  return $suggestions;
}
