#!/usr/bin/env node
'use strict';
const fs = require('fs-extra');
const path = require('path');
const chalk = require('chalk');
const argv = require('minimist')(process.argv.slice(2));
const { globSync } = require('glob');
const ts = require('typescript');

const TRANSLATIONS_FILENAME = 'drupal-gutenberg-translations.js';
// see https://github.com/WordPress/gutenberg/blob/master/packages/i18n/src/index.js
const I18N_FUNCTIONS = ['__', '_x', '_n', '_nx'];

// Two-arg form: <source> <target>. One-arg form: <target> (source defaults
// to CWD). Restricting source to a specific dir is strongly recommended:
// scanning minified build output triggers false positives where mangled
// method names like `r._n(e)` collide with the i18n function names.
const source = argv._.length >= 2 ? argv._[0] : '.';
const target = argv._.length >= 2 ? argv._[1] : argv._[0] || './js';
const verbose = argv.verbose || false;

const fileMatch = '**/*.js';
const globOptions = {
  cwd: source,
  ignore: ['**/node_modules/**', '**/*.es6.js', '**/*.min.js', '**/build/**'],
  nodir: true,
  absolute: true,
};

const warning = (msg) => {
  console.warn(chalk.keyword('orange')(msg));
};

const processFiles = (filePaths) => {
  fs.ensureFileSync(path.join(target, TRANSLATIONS_FILENAME), (err) => {
    console.log(err);
  });

  let content = `/*\n\tFile generated by drupal-gutenberg-translations tool.\n*/\n/*\n`;

  const processEntry = (entry) => {
    const functionName = entry.functionName;
    const key = entry.key;
    const optionsArgument = entry.optionsArgument;

    if (functionName === '__' || functionName === '_x') {
      let argumentValues = `${key}`;
      if (functionName === '_x' && optionsArgument[0]) {
        argumentValues += `, {}, {context:${optionsArgument[0]}}`;
      }
      content += `\tDrupal.t(${argumentValues});\n`;
    } else if (functionName === '_n' || functionName === '_nx') {
      const single = key;
      const plural = optionsArgument[0];
      const number = optionsArgument[1] || 1;
      if (single && plural && number) {
        let argumentValues = `${number}, ${single}, ${plural}`;
        if (functionName === '_nx' && optionsArgument[2]) {
          argumentValues += `,{},{context:${optionsArgument[2]}}`;
        }
        content += `\tDrupal.formatPlural(${argumentValues});\n`;
      }
    }
  };

  const parseTree = (node, sourceFile) => {
    let entry;

    if (node.kind === ts.SyntaxKind.CallExpression) {
      entry = expressionExtractor(node, sourceFile);
    }

    if (entry) {
      if (verbose) {
        if (!sourceFile.processedDrupalTranslation) {
          content += `\t// File ./${sourceFile.fileName}\n`;
          sourceFile.processedDrupalTranslation = true;
        }
      }
      processEntry(entry);
    }

    node.forEachChild((child) => parseTree(child, sourceFile));
  };

  const expressionExtractor = (node, sourceFile) => {
    const entry = {};
    let isTranslationFunction = false;

    if (node.expression.text && I18N_FUNCTIONS.includes(node.expression.text)) {
      isTranslationFunction = true;
      entry.functionName = node.expression.text;
    } else if (
      node.expression.name &&
      I18N_FUNCTIONS.includes(node.expression.name.text)
    ) {
      isTranslationFunction = true;
      entry.functionName = node.expression.name.text;
    } else {
      let firstArgument;

      if (
        ts.SyntaxKind.CallExpression === node.expression.kind &&
        node.expression.arguments[0]
      ) {
        firstArgument = node.expression.arguments[0];
      } else if (
        ts.SyntaxKind.ParenthesizedExpression === node.expression.kind &&
        node.expression.expression
      ) {
        firstArgument = node.expression.expression;
      }
      if (firstArgument) {
        let callName = '';
        if (firstArgument.kind === ts.SyntaxKind.PropertyAccessExpression) {
          callName = firstArgument.name.text;
        } else if (firstArgument.text) {
          callName = firstArgument.text;
        }

        if (callName && I18N_FUNCTIONS.includes(callName)) {
          isTranslationFunction = true;
          entry.functionName = callName;
        }
      }
    }

    if (!isTranslationFunction || !node.arguments || !node.arguments.length) {
      return null;
    }

    const argumentValue = node.arguments.shift();

    if (argumentValue && argumentValue.kind === ts.SyntaxKind.StringLiteral) {
      entry.key = JSON.stringify(argumentValue.text);
    } else if (
      argumentValue &&
      argumentValue.kind === ts.SyntaxKind.BinaryExpression
    ) {
      const concatenatedString = concatenateString(argumentValue);
      if (!concatenatedString) {
        warning(`Key is not a string literal: ${argumentValue.text}`);
        return null;
      }
      entry.key = JSON.stringify(concatenatedString);
    } else {
      if (argumentValue.kind === ts.SyntaxKind.Identifier) {
        warning(`Key is not a string literal: ${argumentValue.text}`);
      }
      return null;
    }

    entry.optionsArgument = node.arguments.map((argument) => {
      if (!argument) {
        return null;
      }
      if (argument.kind === ts.SyntaxKind.StringLiteral) {
        return JSON.stringify(argument.text);
      } else if (argument.kind === ts.SyntaxKind.BinaryExpression) {
        const concatenatedString = concatenateString(argument);
        if (!concatenatedString) {
          warning(`Argument value is not a string literal: ${argument.text}`);
          return null;
        }
        return JSON.stringify(concatenatedString);
      } else if (argument.kind === ts.SyntaxKind.NumericLiteral) {
        return parseInt(argument.text);
      } else if (argument.kind === ts.SyntaxKind.ObjectLiteralExpression) {
        const object = {};
        for (const p of argument.properties) {
          object[p.name.text] = (p.initializer && p.initializer.text) || '';
        }
        return JSON.stringify(object);
      } else if (verbose) {
        warning(
          `Argument value type "${ts.SyntaxKind[argument.kind]}" not supported: ${argument.getText(sourceFile)}`,
        );
      }
      return null;
    });

    return entry;
  };

  const concatenateString = (binaryExpression, string = '') => {
    if (binaryExpression.operatorToken.kind !== ts.SyntaxKind.PlusToken) {
      return;
    }

    if (binaryExpression.left.kind === ts.SyntaxKind.BinaryExpression) {
      string += concatenateString(binaryExpression.left, string);
    } else if (binaryExpression.left.kind === ts.SyntaxKind.StringLiteral) {
      string += binaryExpression.left.text;
    } else {
      return;
    }

    if (binaryExpression.right.kind === ts.SyntaxKind.BinaryExpression) {
      string += concatenateString(binaryExpression.right, string);
    } else if (binaryExpression.right.kind === ts.SyntaxKind.StringLiteral) {
      string += binaryExpression.right.text;
    } else {
      return;
    }

    return string;
  };

  filePaths.forEach((filePath) => {
    if (verbose) {
      console.log(`Parsing ${filePath}`);
    }

    const data = fs.readFileSync(filePath, { encoding: 'utf-8' });
    const sourceFile = ts.createSourceFile(
      filePath,
      data,
      ts.ScriptTarget.Latest,
    );
    parseTree(sourceFile, sourceFile);
  });

  content += '*/\n';

  fs.writeFileSync(path.join(target, TRANSLATIONS_FILENAME), content);
};

console.log(`${chalk.red('🏳 Drupal Gutenberg Translations Builder')}`);
console.log(
  `${chalk.green('Target file')}: ${chalk.white(path.join(target, TRANSLATIONS_FILENAME))}`,
);

try {
  const filePaths = globSync(fileMatch, globOptions);
  processFiles(filePaths);
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
