<?php

namespace Drupal\gutenberg\BlockProcessor;

use Drupal\Component\Render\MarkupInterface;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\gutenberg\StyleEngine;

/**
 * Processes Gutenberg blocks with __experimentalSettings support.
 *
 * Thin Drupal adapter that delegates to synced upstream functions from
 * WordPress/gutenberg lib/block-supports/settings.php.
 *
 * Adds a deterministic wp-settings-* class to the block wrapper so that
 * per-block CSS custom property overrides (color/typography presets set via
 * the block inspector) can be scoped to that block instance. The CSS itself
 * is generated by _gutenberg_add_block_level_preset_styles() (diffOnly —
 * requires WP_Theme_JSON_Gutenberg), which is not yet ported; only the
 * class-name application is handled here.
 */
class SettingsProcessor implements GutenbergBlockProcessorInterface {

  /**
   * {@inheritdoc}
   */
  public function processBlock(array &$block, &$block_content, RefinableCacheableDependencyInterface $bubbleable_metadata) {
    class_exists(StyleEngine::class);

    if ($block_content instanceof MarkupInterface) {
      $block_content = $block_content->__toString();
    }

    $block_content = \_gutenberg_add_block_level_presets_class($block_content, $block);
    return $block_content;
  }

  /**
   * {@inheritdoc}
   */
  public function isSupported(array $block, $block_content = '') {
    return !empty($block['attrs']['settings']) && !empty($block['blockName']);
  }

}
